FROM haproxy:2.5

USER root

# Install rsyslog
RUN apt-get update && \
  apt-get -y install rsyslog && \
  rm -rf /var/lib/apt/lists/*


ADD rsyslog/haproxy.conf /etc/rsyslog.d
ADD rsyslog/rsyslog.conf /etc/rsyslog.conf

COPY docker-entrypoint.sh /

# Optional ENV var you could override:
# HAPROXY_CFG_FILE setup the full path (in the container) where to load the HAproxy config

#EXPOSE 80 443 1883 8883 1988

#RUN usermod -a -G haproxy root

#USER haproxy

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["haproxy", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]
